spring.application.name=elearning-platform

server.port=8084

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/elearning_db
spring.datasource.username=postgres
spring.datasource.password=Support@2525

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=MaCleSecreteSuperLongue1234567890ABCDEF
app.jwt.expiration-ms=86400000

# Admin par defaut	
app.admin.email=admin@school.com
app.admin.password=Admin@123
app.admin.nom=Admin
app.admin.prenom=System

file.upload-dir=uploads/photos
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cle API OpenAI
openai.api.url=http://localhost:11434/v1/
# Ollama n'a pas besoin de cle, mais le code en attend une
openai.api.key=ollama  
#openai.model=phi3
openai.model=phi3
openai.max-tokens=4000

spring.jackson.serialization.write-dates-as-timestamps=false



